services:
  inseat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: inseat-backend:latest
    container_name: inseat-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - KAFKA_BROKERS=kafka:29092
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3001/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - inseat-network
    depends_on:
      - redis
      - kafka

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inseat-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - inseat-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - inseat-network

networks:
  inseat-network:
    driver: bridge

volumes:
  mongodb_data:
