name: Deploy Customer Menu to Production

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    name: Build and Deploy Customer Menu to Production Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        # Debug DNS resolution
        echo "Attempting to connect to: ${{ secrets.SERVER_HOST }}"
        nslookup ${{ secrets.SERVER_HOST }} || echo "DNS lookup failed"
        
        # Create temporary directory for upload
        ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /tmp/customer-menu-dist"
        
        # Upload new build
        scp -o ConnectTimeout=30 -o StrictHostKeyChecking=no -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/tmp/customer-menu-dist/
        
        # Deploy to production location
        ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          echo "Starting deployment to production..."
          sudo mkdir -p /var/www/inseat-customer.backup.$(date +%Y%m%d_%H%M%S)
          sudo cp -r /var/www/inseat-customer/* /var/www/inseat-customer.backup.$(date +%Y%m%d_%H%M%S)/ 2>/dev/null || true
          echo "Checking temp directory contents:"
          ls -la /tmp/customer-menu-dist/
          sudo rm -rf /var/www/inseat-customer/*
          sudo cp -r /tmp/customer-menu-dist/* /var/www/inseat-customer/
          sudo chown -R www-data:www-data /var/www/inseat-customer
          sudo chmod -R 755 /var/www/inseat-customer
          echo "Production deployment completed. Final directory contents:"
          ls -la /var/www/inseat-customer/
          rm -rf /tmp/customer-menu-dist
        EOF

    - name: Verify deployment
      run: |
        ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          if [ -f "/var/www/inseat-customer/index.html" ]; then
            echo "✅ Customer Menu Production deployment successful!"
            echo "Deployment timestamp: $(stat -c %y /var/www/inseat-customer/index.html)"
          else
            echo "❌ Deployment failed - index.html not found"
            exit 1
          fi
        EOF
